-- return {
-- 	"nvim-neo-tree/neo-tree.nvim",
-- 	version = "v3.x",
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim",
-- 		"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
-- 		"MunifTanjim/nui.nvim",
-- 	},
-- 	lazy = false,
-- 	---@module "neo-tree"
-- 	---@type neotree.Config?
-- 	opts = {
-- 		-- fill any relevant options here
-- 	},
--
-- 	config = function()
-- 		require("neo-tree").setup({
-- 			close_if_last_window = true,
-- 			filesystem = {
-- 				follow_current_file = {
-- 					enabled = true, -- This will find and focus the file in the active buffer every time
-- 					--                        -- the current file is changed while the tree is open.
-- 					leave_dirs_open = false, -- `false` closes auto expanded dirs, such as with `:Neotree reveal`
-- 				},
-- 			},
-- 		})
-- 	end,
-- }
--

return {}
